---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lajix/public_html/mastergolf.lajix.com/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R membership $DEPLOYPATH
    - /bin/cp -R news $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH